spring:
  datasource:
    url: jdbc:mysql://localhost:3306/commandedb?user=root
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 7E19F35CDEamine*
  jpa:
    hibernate:
      ddl-auto: update  
    database-platform: org.hibernate.dialect.MySQL8Dialect





mes-config-ms:
  commandes-last: 4
